use std::{
    any::Any,
    sync::{Arc, Mutex},
};

use bevy::{
    ecs::system::{SystemMeta, SystemParam},
    prelude::*,
};

use crate::{not_system_meta::NotSystemMeta, NodeSpan, PresenterFn, ViewContext};

use super::{cx::Cx, PresenterParam, View};

/// A ViewHandle holds a type-erased reference to a presenter function and its props and state.
#[derive(Component)]
pub struct ViewHandle {
    /// A reference to the type-erased presenter state.
    pub inner: Arc<Mutex<dyn AnyPresenterState>>,
}

impl ViewHandle {
    /// Construct a new ViewRoot from a presenter and props.
    pub fn new<Marker, P: PresenterFn<Marker>>(presenter: P, props: P::Props) -> Self {
        Self {
            inner: Arc::new(Mutex::new(PresenterState::new(presenter, props))),
        }
    }

    /// Update the copy of props in this view state.
    pub fn update_props<'a>(&mut self, props: &'a dyn Any) -> bool {
        self.inner.lock().unwrap().update_props(props)
    }
}

/// `ViewState` contains all of the data needed to re-render a presenter: The presenter function,
/// its properties, its state, and the cached output nodes.
///
/// This type is generic on the props and state for the presenter.
pub struct PresenterState<Marker: 'static, F: PresenterFn<Marker>> {
    /// Reference to presenter function
    presenter: F,

    /// Props passed to the presenter
    props: F::Props,

    /// View tree output by presenter
    view: Option<F::View>,

    /// Externalized state defined by view tree
    state: Option<<F::View as View>::State>,

    /// The UiNodes generated by this view state
    nodes: NodeSpan,
}

impl<Marker, F: PresenterFn<Marker>> PresenterState<Marker, F> {
    pub fn new(presenter: F, props: F::Props) -> Self {
        Self {
            presenter,
            nodes: NodeSpan::Empty,
            props,
            view: None,
            state: Option::None,
        }
    }
}

/// `AnyViewState` is a type-erased version of `ViewState`. It allows holding a reference
/// to a renderable presenter without knowing the type of its props and state.
pub trait AnyPresenterState: Send {
    /// Return the nodes that were generated by this view.
    fn nodes(&self) -> NodeSpan;

    /// Rebuild the NodeSpans for this view and update the state.
    fn build(&mut self, vc: &mut ViewContext, entity: Entity);

    /// Release all state and despawn all child entities.
    fn raze(&mut self, vc: &mut ViewContext, entity: Entity);

    /// Rebuild the display graph connections.
    fn attach(&mut self, vc: &mut ViewContext, entity: Entity);

    /// Update the copy of props in this view state.
    fn update_props<'a>(&mut self, props: &'a dyn Any) -> bool;
}

impl<Marker, F: PresenterFn<Marker>> AnyPresenterState for PresenterState<Marker, F> {
    fn build(&mut self, vc: &mut ViewContext, entity: Entity) {
        let mut child_context = ViewContext::new(vc.world, entity);
        let cx = Cx::new(&self.props, entity);
        F::Param::add_tracking(&mut child_context);
        // TODO: Store system_meta and param_state somewhere instead of re-instantiating each build
        let mut system_meta =
            unsafe { std::mem::transmute::<_, SystemMeta>(NotSystemMeta::new::<Marker>()) };
        let mut param_state =
            <F::Param as SystemParam>::init_state(&mut child_context.world, &mut system_meta);
        let world_cell = child_context.world.as_unsafe_world_cell();
        let param_item = unsafe {
            <F::Param as SystemParam>::get_param(
                &mut param_state,
                &system_meta,
                world_cell,
                world_cell.change_tick(),
            )
        };
        self.view = Some(self.presenter.build(cx, param_item));
        match self.state {
            Some(ref mut state) => {
                self.view
                    .as_ref()
                    .unwrap()
                    .update(&mut child_context, state);
                self.attach(vc, entity);
            }
            None => {
                let state = self.view.as_ref().unwrap().build(&mut child_context);
                self.state = Some(state);
                vc.mark_changed_shape();
                if let Some(parent) = vc.entity(vc.entity).get::<Parent>() {
                    vc.entity_mut(parent.get()).insert(PresenterGraphChanged);
                }
            }
        };
    }

    fn raze(&mut self, vc: &mut ViewContext, entity: Entity) {
        let mut child_context = ViewContext::new(vc.world, entity);
        if let Some(ref view) = self.view {
            // Despawn the presenter state entity.
            if let Some(ref mut state) = self.state {
                view.raze(&mut child_context, state);
            }
            self.view = None;
            self.state = None;
        }
    }

    fn attach(&mut self, vc: &mut ViewContext, entity: Entity) {
        let mut child_context = ViewContext::new(vc.world, entity);
        let nodes = self
            .view
            .as_ref()
            .unwrap()
            .assemble(&mut child_context, &mut self.state.as_mut().unwrap());
        if self.nodes != nodes {
            self.nodes = nodes;
            // Parent needs to rebuild children
            if let Some(parent) = vc.entity(vc.entity).get::<Parent>() {
                vc.world
                    .entity_mut(parent.get())
                    .insert(PresenterGraphChanged);
            }
        }
    }

    fn nodes(&self) -> NodeSpan {
        self.nodes.clone()
    }

    fn update_props<'a>(&mut self, new_props: &'a dyn Any) -> bool {
        let new_props = new_props
            .downcast_ref::<F::Props>()
            .expect("Mismatched props type");

        if self.props != *new_props {
            self.props.clone_from(new_props);
            true
        } else {
            false
        }
    }
}

/// Marker component that lets us know when the internal state of a presenter needs to be
/// rebuilt.
#[derive(Component)]
pub struct PresenterStateChanged;

/// Marker component that lets us know when the display graph for a presenter needs to be
/// rebuilt.
#[derive(Component)]
pub struct PresenterGraphChanged;
